
export const ENV = {
  NEXTAUTH_URL: process.env.NEXTAUTH_URL ,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_BACKEND_URL: process.env.NEXTAUTH_BACKEND_URL ,
  NEXTAUTH_BACKEND_URL: process.env.NEXTAUTH_BACKEND_URL ,
};


export const API = {
  BASE_URL: ENV.NEXTAUTH_BACKEND_URL,
  IMAGE_URL: `${ENV.NEXTAUTH_BACKEND_URL}/api/image`,
};